### ISSUE TITLE
Bigger data with Apache arrow

### ISSUE THREAD

**Issue by jthomasmock** [thisisnic/awesome-arrow#1]
Love this idea!

I have a slide deck (need to give it as a public webinar eventually) that I've used for trainings/overviews.

[https://jthomasmock.github.io/bigger-data/](https://jthomasmock.github.io/bigger-data/#1) and corresponding [GH Repo](https://github.com/jthomasmock/bigger-data)

**Comment by thisisnic** [comment]
Added now, thanks - and let me know when you give it as a public webinar and I'll add a link to it!
